version: '3.8'

services:
  jobchain-db:
    image: mongo
    # volumes:
    #   - type: bind
    #     source: ../../data
    #     target: /data/db
    container_name: jobchain-db
    ports:
      - 27018:27017
    networks:
      - jobchain-network

  jobchain:
    container_name: jobchain
    image: jobchain.1.1
    build:
      context: ../../
      # target: development
      dockerfile: ./iac/docker/Dockerfile
    # command: npm run start:dev
    command: node dist/main
    ports:
      - 3002:3000
      - 9228:9229
    networks:
      - jobchain-network
    volumes:
      - ../../:/jobchain
      - /jobchain/node_modules
    restart: unless-stopped
    depends_on:
      - jobchain-db

    # env_file:
    #   - ../../iac/docker/.env.docker.dev

networks:
  jobchain-network:
