version: '3.8'

services:
  jobchain-db:
    image: mongo
    container_name: jobchain-db
    ports:
      - 27018:27017
    networks:
      - jobchain-network

  jobchain:
    container_name: jobchain
    image: jobchain:1.0.0
    build:
      context: ../../
      dockerfile: ./iac/docker/Dockerfile

    env_file:
      - .env.docker
    ports:
      - 3002:3000
      - 9228:9229
    networks:
      - jobchain-network
    volumes:
      - ../../:/jobchain
      - /jobchain/node_modules
    restart: unless-stopped
    command: node dist/main

    depends_on:
      - jobchain-db

networks:
  jobchain-network:
